try {
    console.log('Put de code');
    const yeffer = 'a'
    yeffer = 10
} catch (error) {
    console.log(`The mistake is ${error}`);
}finally{

    console.log('always iam here');

}